<?php

namespace Database\Seeders;

use App\Models\Branch;
use App\Models\Category;
use App\Models\Inventory;
use Carbon\Carbon;
use Faker\Factory as Faker;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class InventorySeeder extends Seeder
{

    public const UnitOfMeasurementMT = 'mt';
    public const UnitOfMeasurementKg = 'kg';
    public const UnitOfMeasurementPcs = 'Pcs';
    public const UnitOfMeasurementCtn = 'Ctn(s)';
    public const UnitOfMeasurementYard = 'Yard(s)';


    public function run()
    {
            $lagosBranch = Branch::getBranch(1)->id;
            $LpgGas = Category::getCategory(1)->id;   // LPG Gas Refill
            $lpgAccessories = Category::getCategory(2)->id;   // LPG Accessories
            $lpgCylinder = Category::getCategory(3)->id;   // LPG Cylinders

        Schema::disableForeignKeyConstraints();
        DB::table('inventories')->truncate();

        DB::table('inventories')->insert([
                 [
                    'name' => '1000',
                    'quantity' => 10000,
                    'category_id' => $LpgGas,
                    'dealer_price' => 736000,
                    'price' => 712000,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'staff_price' => 0,
                    'unit_of_measurement' => self::UnitOfMeasurementMT,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],

                [
                    'name' => '10',
                    'quantity' => 1000,
                    'category_id' => $LpgGas,
                    'dealer_price' => 7120,
                    'price' => 7360,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'staff_price' => 4420,
                    'unit_of_measurement' => self::UnitOfMeasurementKg,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],

                [
                    'name' => '12.5',
                    'quantity' => 1000,
                    'category_id' => $LpgGas,
                    'price' => 9200,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'staff_price' => 5520,
                    'dealer_price' => 8900,
                    'unit_of_measurement' => self::UnitOfMeasurementKg,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'name' => '15',
                    'quantity' => 1000,
                    'category_id' => $LpgGas,
                    'price' => 11040,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'staff_price' => '',
                    'dealer_price' => 10680,
                    'unit_of_measurement' => self::UnitOfMeasurementKg,
                    'crs_price' => '',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],

                [
                    'name' => '1',
                    'quantity' => 1000,
                    'category_id' => $LpgGas,
                    'dealer_price' => 720,
                    'price' => 740,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'staff_price' => 450,
                    'unit_of_measurement' => self::UnitOfMeasurementKg,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],

                [
                    'name' => '20',
                    'quantity' => 1000,
                    'category_id' => $LpgGas,
                    'dealer_price' => 14240,
                    'price' => 14720,
                    'staff_price' => 0,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementKg,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'name' => '25',
                    'quantity' => 1000,
                    'category_id' => $LpgGas,
                    'dealer_price' => 17800,
                    'price' => 18400,
                    'staff_price' => 0,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementKg,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],

                [
                    'name' => '2',
                    'quantity' => 1000,
                    'category_id' => $LpgGas,
                    'dealer_price' => 1420,
                    'price' => 1480,
                    'staff_price' => 890,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementKg,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],

                [
                    'name' => '37.5',
                    'quantity' => 1000,
                    'category_id' => $LpgGas,
                    'dealer_price' => 26700,
                    'price' => 27600,
                    'staff_price' => 0,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementKg,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'name' => '4',
                    'quantity' => 1000,
                    'category_id' => $LpgGas,
                    'dealer_price' => 2840,
                    'price' => 2960,
                    'staff_price' => 1780,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementKg,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],


                [
                    'name' => '5',
                    'quantity' => 100,
                    'category_id' => $LpgGas,
                    'dealer_price' => 3569,
                    'price' => 3560,
                    'staff_price' => 2210,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementKg,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'name' => '50l',
                    'quantity' => 1000,
                    'category_id' => $LpgGas,
                    'dealer_price' => 35600,
                    'price' => 36800,
                    'staff_price' =>0,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementKg,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'name' => '3',
                    'quantity' => 1000,
                    'category_id' => $LpgGas,
                    'dealer_price' => 2140,
                    'price' => 2210,
                    'staff_price' => 1330,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementKg,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'name' => '6',
                    'quantity' => '1000',
                    'category_id' => $LpgGas,
                    'dealer_price' => 4280,
                    'price' => 4420,
                    'staff_price' => 2650,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementKg,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'name' => '8',
                    'quantity' => 1000,
                    'category_id' => $LpgGas,
                    'dealer_price' => 5700,
                    'price' => 5890,
                    'staff_price' => 3540,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementKg,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],

                [
                    'name' => '50',
                    'quantity' => 1000,
                    'category_id' => $lpgCylinder,
                    'dealer_price' => 5000,
                    'price' => 5000,
                    'staff_price' => 5000,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementPcs,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'name' => 'Burner',
                    'quantity' => 1000,
                    'category_id' => $lpgAccessories,
                    'dealer_price' => 5000,
                    'price' => 5000,
                    'staff_price' => 5000,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementPcs,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'name' => 'Camping Regulator',
                    'quantity' => 1000,
                    'category_id' => $lpgAccessories,
                    'dealer_price' => 5000,
                    'price' => 5000,
                    'staff_price' => 5000,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementCtn,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'name' => 'Camping Valve',
                    'quantity' => 1000,
                    'category_id' => $lpgAccessories,
                    'dealer_price' => 5000,
                    'price' => 5000,
                    'staff_price' => 5000,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementPcs,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'name' => 'Clips',
                    'quantity' => 1000,
                    'category_id' => $lpgCylinder,
                    'dealer_price' => 5000,
                    'price' => 5000,
                    'staff_price' => 5000,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementPcs,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'name' => 'Cylinder (12.5kg)',
                    'quantity' => 1000,
                    'category_id' => $lpgCylinder,
                    'dealer_price' => 5000,
                    'price' => 5000,
                    'staff_price' => 5000,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementPcs,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'name' => 'Cylinder (3KG)',
                    'quantity' => 1000,
                    'category_id' => $lpgCylinder,
                    'dealer_price' => 5000,
                    'price' => 5000,
                    'staff_price' => 5000,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementPcs,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'name' => 'Cylinder (6kg)',
                    'quantity' => 1000,
                    'category_id' => $lpgCylinder,
                    'dealer_price' => 5000,
                    'price' => 5000,
                    'staff_price' => 5000,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementPcs,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'name' => 'Hose',
                    'quantity' => 1000,
                    'category_id' => $lpgAccessories,
                    'dealer_price' => 5000,
                    'price' => 5000,
                    'staff_price' => 5000,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementYard,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'name' => 'Nido Regulator',
                    'quantity' => 1000,
                    'category_id' => $lpgAccessories,
                    'dealer_price' => 5000,
                    'price' => 5000,
                    'staff_price' => 5000,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementCtn,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'name' => 'Nido Valve',
                    'quantity' => 1000,
                    'category_id' => $lpgAccessories,
                    'dealer_price' => 5000,
                    'price' => 5000,
                    'staff_price' => 5000,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementCtn,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'name' => 'Standard Regulator',
                    'quantity' => 1000,
                    'category_id' => $lpgAccessories,
                    'dealer_price' => 5000,
                    'price' => 5000,
                    'staff_price' => 5000,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementPcs,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'name' => 'Standard Valves',
                    'quantity' => 1000,
                    'category_id' => $lpgAccessories,
                    'dealer_price' => 5000,
                    'price' => 5000,
                    'staff_price' => 5000,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementPcs,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'name' => 'UGL Table Cooker',
                    'quantity' => 1000,
                    'category_id' => $lpgAccessories,
                    'dealer_price' => 5000,
                    'price' => 5000,
                    'staff_price' => 5000,
                    'branch_id' => $lagosBranch,
                    'barcode' => '',
                    'unit_of_measurement' => self::UnitOfMeasurementPcs,
                    'crs_price' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
            ]);
    }
}


